---
downloads: ~/.ansible-downloads/

# PHP
install_php: true
install_composer: true

# Browser
install_chrome: true

# Docker
install_docker: true
docker_compose_version: "1.28.0"
docker_users: ["{{ ansible_env.USER }}"]

# Development environment tool using Docker
install_lando: true

# ZSH
install_zsh: true
antigen_users:
  - username: "{{ ansible_env.USER }}"
    antigen_libraries:
      - name: oh-my-zsh
    antigen_theme:
      name: robbyrussell
    antigen_bundles:
      - name: command-not-found
      - name: git
      - name: nvm
      - name: aws
      - name: kubectl
antigen_bundle_users:
  - username: "{{ ansible_env.USER }}"
    antigen_bundles:
      - name: zsh-completions
        url: zsh-users/zsh-completions
      - name: zsh-autosuggestions
        url: zsh-users/zsh-autosuggestions
      - name: zsh-syntax-highlighting
        url: zsh-users/zsh-syntax-highlighting

configure_zshrc: true

# AWS cli
install_aws: true

# K8s
install_kubectl: true
install_minikube: true
install_helm: true

install_lens: true
lens_version: 5.4.6-latest.20220428.1

# CLI for interacting with a Lagoon instance
install_lagoon: true
lagoon_version: v0.12.3

# Node
install_nvm: true
install_yarn: true

# IDEs
install_jetbrains_toolbox: true
toolbox_version: "1.24.11947"

install_vscode: true

# Task execution tool
install_invoke: true

# Music
install_spotify: true

# Password manager
install_bitwarden: true

# IM apps
install_mattermost: true
mattermost_version: 5.0.4

install_slack: true
slack_version: 4.25.0

# Tool for adjusting webcam settings
install_camset: true

# Screen capture to gif utility
install_peek: true

# Sets the hardware clock to use the local timezone rather than UTC.
# This is useful when dual booting with windows.
hw_clock_local_timezone: true
