---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags:
        - always
    - name: Set ansible_distribution to Ubuntu
      set_fact: ansible_distribution="Ubuntu"
      tags:
        - always
    - name: Install PHP
      include_task: tasks/php.yml
      when: install_php
      become: true
      tags:
        - php

  roles:
    - role: geerlingguy.composer
      when: install_composer
      become: true
      tags:
        - php
        - composer
    - role: darkwizard242.googlechrome
      when: install_chrome
      become: true
      tags:
        - chrome
    - role: geerlingguy.docker
      when: install_docker
      become: true
      tags:
        - docker
    - role: gantsign.antigen
      when: install_zsh
      become: true
      users: "{{antigen_users}}"
      tags:
        - zsh
        - antigen
    - role: gantsign.antigen_bundles
      when: install_zsh
      become: true
      users: "{{antigen_bundle_users}}"
      tags:
        - zsh
        - antigen_bundles
    - role: webarchitect609.jet_brains_toolbox
      when: install_jetbrains_toolbox
      become: true
      tags:
        - jetbrains_toolbox
    - role: ngetchell.vscode
      when: install_vscode
      become: true
      tags:
        - vscode

  tasks:
    - name: Install NVM
      include_task: tasks/nvm.yml
      when: install_nvm
      tags:
        - node
        - nvm

    - name: Install Lando
      include_task: tasks/lando.yml
      when: install_lando
      become: true
      tags:
        - lando

    - name: Install AWS Cli
      include_task: tasks/awscli.yml
      when: install_aws
      become: true
      tags:
        - awscli

    - name: Install kubectl
      include_task: tasks/kubectl.yml
      when: install_kubectl
      become: true
      tags:
        - kubectl
        - k8s

    - name: Install minikube
      include_task: tasks/minikube.yml
      when: install_minikube
      become: true
      tags:
        - minikube
        - k8s

    - name: Install helm
      include_task: tasks/helm.yml
      when: install_helm
      become: true
      tags:
        - helm
        - k8s

    - name: install lens
      include_task: tasks/lens.yml
      when: install_lens
      become: true
      tags:
        - lens
        - k8s

    - name: install lagoon
      include_task: tasks/lagoon.yml
      when: install_lagoon
      become: true
      tags:
        - lagoon
        - k8s

    - name: Install Spotify
      include_task: tasks/spotify.yml
      when: install_spotify
      tags:
        - spotify

    - name: Install Bitwarden
      include_task: tasks/bitwarden.yml
      when: install_bitwarden
      tags:
        - bitwarden

    - name: Install Slack
      include_task: tasks/slack.yml
      when: install_slack
      become: true
      tags:
        - slack

    - name: Install Mattermost Desktop
      include_task: tasks/mattermost.yml
      when: install_mattermost
      become: true
      tags:
        - mattermost

    - name: Set .zshrc
      include_task: tasks/zshrc.yml
      when: configure_zshrc
      tags:
        - zshrc

    - name: Install camset
      include_task: tasks/camset.yml
      when: install_camset
      become: true
      tags:
        - camset

    - name: Install invoke
      include_task: tasks/invoke.yml
      when: install_invoke
      become: true
      tags:
        - invoke

    - name: Install peek
      include_task: tasks/peek.yml
      when: install_peek
      become: true
      tags:
        - peek

    - name: Set hardware clock to local timezone
      include_task: tasks/hwclock.yml
      when: hw_clock_local_timezone
      tags:
        - hwclock
