---
- name: check if lagoon cli is installed
  stat:
    path: /usr/local/bin/lagoon
  register: stat_result

- name: Download lagoon binary
  get_url:
    url: https://github.com/amazeeio/lagoon-cli/releases/download/{{ lagoon_version }}/lagoon-cli-{{ lagoon_version }}-linux-amd64
    dest: /usr/local/bin/lagoon
  become: true
  when: not stat_result.stat.exists

- name: Ensure lagoon binary is executable
  file:
    path: /usr/local/bin/lagoon
    mode: '0755'
  when: not stat_result.stat.exists