---
- name: Only run update cache if the last one is more than 3600 seconds ago
  apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install pavucontrol
  apt:
    name: pavucontrol
    state: present
